### ISSUE TITLE
タイムライン　マークアップ移植

### ISSUE THREAD

**Issue by yaotani0413** [yaotani0413/SAMPLE_Project#10]

**Comment by yaotani0413** [comment]
わからないところを記載しておきます。
①ヘッダーコンポーネントがうまく作れないです。
以下のように適当にヘッダー表示用のファイル作成してやってみましたが、うまくいきません…。
![スクリーンショット 2020-06-23 22 09 32](https://user-images.githubusercontent.com/62005212/85407605-5e504300-b59e-11ea-9952-57677f7012aa.png)
![スクリーンショット 2020-06-23 22 09 35](https://user-images.githubusercontent.com/62005212/85407615-614b3380-b59e-11ea-9fda-821a9222fcaf.png)

**Comment by yaotani0413** [comment]
②作成していただいた「header__padding」クラスのdivがなんのために存在しているかがわからないです。
![スクリーンショット 2020-06-23 22 03 52](https://user-images.githubusercontent.com/62005212/85407860-ba1acc00-b59e-11ea-9246-fbac658a087c.png)
![Uploading スクリーンショット 2020-06-23 22.03.52（2）.png…]()

**Comment by yaotani0413** [comment]
③headerクラスにつけている`z-index: 10;`がどういう効果となっているかわからないです。
z-indexが重ね合わせの順番？であることは確か前に学びました。
![スクリーンショット 2020-06-23 22 05 08](https://user-images.githubusercontent.com/62005212/85408203-2c8bac00-b59f-11ea-82d2-24ff5697da89.png)

**Comment by yaotani0413** [comment]
①のヘッダーコンポーネント解決いたしました。
⇨`<header />`が表示されず、`<Header />`で解決。

**Comment by TakehiroTada** [comment]
>①のヘッダーコンポーネント解決いたしました。
⇨<header />が表示されず、<Header />で解決。
これなのですが、おっしゃる通り `header` タグと Headerコンポーネントの名前が競合しているのが原因です。　が、しかしtemplateタグ内に書かれるタグ名はケバフケースが好ましいので
https://designsupply-web.com/developmentlab/4052/

コンポーネント名を変更すると良いかもです。
例えば `TheHeader` にして templateタグ内は `the-header` とするわけです

**Comment by TakehiroTada** [comment]
> ②作成していただいた「header__padding」クラスのdivがなんのために存在しているかがわからないです。

これは、実際に外してみて頂くとわかりますがヘッダーを `position: fixed` で固定しているため、paddingで作られた空白が無いと隠れちゃうんですよね。その時の対処テクニックです。
こちらの記事が参考になりそうです
https://tanomasaki.com/tech/headernav-fixed/

**Comment by TakehiroTada** [comment]
>③headerクラスにつけているz-index: 10;がどういう効果となっているかわからないです。
z-indexが重ね合わせの順番？であることは確か前に学びました。

これはおっしゃる通り素直に「ヘッダーを前面に持ってきたいのでとりあえず10ぐらいつけておいた」という感覚です。

**Comment by yaotani0413** [comment]
理解できました！ありがとうございます。

**Comment by TakehiroTada** [comment]
解決した場合にはcloseしちゃいましょー
