### ISSUE TITLE
ツイート部分をコンポーネント化

### ISSUE THREAD

**Issue by TakehiroTada** [yaotani0413/SAMPLE_Project#14]
ツイート部分（画像参照）を単体でコンポーネント化した後にmap関数でTweetScreen内に複数表示してみましょう

![image](https://user-images.githubusercontent.com/40785892/85913247-e91a9180-b86d-11ea-9000-6861b82f5422.png)

map関数について（少し難しいと思うので質問していただいても大丈夫です）
https://qiita.com/ryosuketter/items/c11a58242fa1ad9c6e4c

**Comment by TakehiroTada** [comment]
ごめんなさい！！　完全にReact向けの記事を貼ってましたねｗｗｗｗｗ
Nuxtだとこの方法はさっぱりだと思います（一応出来るのですが）

やるべきことは
- ↑の写真部分をコンポーネント化して切ります
- v-forでリストレンダリングする

でした。
https://jp.vuejs.org/v2/guide/list.html

**Comment by yaotani0413** [comment]
ガッツリReactって書いてて困惑してました。
(出来るんですね…！)

やってみますー！

**Comment by yaotani0413** [comment]
自分メモ
■TweetScreenより内容をTweetとしてコンポーネント化

■投稿内容(tweets)はオブジェクトでdataへ記載
`{
          id: 2,
          name: "やまだたろう",
          text: "晩御飯食べたい",
          image_url:
            "https://1.bp.blogspot.com/-jlZlCg-8FAM/Xub_u8HTD1I/AAAAAAABZis/ZhUI05AZBEQpVinedZ6Xy-eIucmNuY2SQCNcBGAsYHQ/s1600/pose_pien_uruuru_man.png"
        }`

■tweetタグにv-forの追加をして子コンポーネント への受け渡し準備。内容は↓
`<tweet
      v-for="tweet in tweets"
      :key="tweet.id"
      :name="tweet.name"
      :text="tweet.text"
      :image-url="tweet.image_url"
    />`

※:keyはユニークなことを識別できればどれを指定しても良いがidを指定することが多い。

■親コンポーネントからデータ受け渡しとしてpropsを設定。親コンポーネントのv-for内の記述と連動。
`export default {
  props: {
    name: {
      type: String,
      required: true
    },
    text: {
      type: String,
      required: true
    },
    imageUrl: {
      type: String,
      required: true
    }
  }
};`
■子コンポーネント(Tweet)で受け取ったデータを反映
`<div class="tweet-container">
    <figure class="thumbnail">
      <img :src="imageUrl" alt="サムネイル" />
    </figure>
    <div class="other">
      <div class="user-name">{{ name }}</div>
      <div class="tweet">{{ text }}</div>
    </div>
  </div>`

※figureは図であることを表すタグ。
※imgタグはalt属性もしっかり記述する。
※{{}}内はpropsで受け取ったものを記述。
